[colors.bright]
black = "#494949"
blue = "#0486FF"
cyan = "#5FD8FF"
green = "#1CD760"
magenta = "#B05FFF"
red = "#FF3B30"
white = "#FFFFFF"
yellow = "#FFCC00"

[colors.cursor]
cursor = "#FF01AF"
text = "CellBackground"

[colors.normal]
black = "#DDDDDD"
blue = "#0486FF"
cyan = "#5FD8FF"
green = "#1CD760"
magenta = "#B05FFF"
red = "#FF3B30"
white = "#FFFFFF"
yellow = "#FFCC00"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"
